spring:
  application:
    name: "twitt"
  cloud.stream:
    function:
      definition: convertPostCdcToPostMessage;commentUserJoiner;joinPost;updatePostCommentCount;joinPostWithUser;materializeEnrichedPost;aggregateActivities;

    bindings:
      # Post Transformer
      convertPostCdcToPostMessage-in-0:
        destination: post-created
      convertPostCdcToPostMessage-out-0:
        destination: post-transformed

      # Comment User Joiner
      commentUserJoiner-in-0:
        destination: comment-created
      commentUserJoiner-in-1:
        destination: user-updated
      commentUserJoiner-out-0:
        destination: comment-user-joined

      # Post Comment Count Update
      updatePostCommentCount-in-0:
        destination: comment-user-joined

      # Join Post User
      joinPostWithUser-in-0:
        destination: post-transformed
      joinPostWithUser-in-1:
        destination: user-updated
      joinPostWithUser-out-0:
        destination: post-user-joined

      # Post Joiner
      joinPost-in-0:
        destination: comment-user-joined
      joinPost-in-1:
        destination: activity-aggregated
      joinPost-in-2:
        destination: post-user-joined
      joinPost-out-0:
        destination: post-joined

      # Joined Post Materialize
      materializeEnrichedPost-in-0:
        destination: post-joined

      # Aggregate activities
      aggregateActivities-in-0:
        destination: activity-updated
      aggregateActivities-out-0:
        destination: activity-aggregated

    kafka:
      streams:
        bindings:
          commentUserJoiner-in-0:
            consumer:
              start-offset: earliest
              materialized-as: comment-user-state-store
          convertPostCdcToPostMessage-in-0:
            consumer:
              start-offset: earliest
          joinPost-in-0:
            consumer:
              start-offset: earliest
              materialized-as: joined-post-state-store

        binder:
          functions:
            convertPostCdcToPostMessage:
              application-id: "convertPostCdcToPostMessage"
            joinPost:
              application-id: "joinPost"
            joinPostWithUser:
              application-id: "joinPostWithUser"
            commentUserJoiner:
              application-id: "commentUserJoiner"
            updatePostCommentCount:
              application-id: "updatePostCommentCount"
            materializeEnrichedPost:
              application-id: "materializeEnrichedPost"
            aggregateActivities:
              application-id: "aggregateActivities"

          brokers: localhost:9092
          configuration:
            processing:
              guarantee: exactly_once
            max.poll.records: 10
            max.poll.interval.ms: 10000

