spring:
  application:
    name: "twitt"
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            processing:
              guarantee: exactly_once
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/twitt
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
bootstrap-servers: localhost:9092