spring:
  application:
    name: "twitt"
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          configuration:
            processing:
              guarantee: exactly_once