spring:
  application:
    name: "twitt"
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            processing:
              guarantee: exactly_once
bootstrap-servers: localhost:9092