spring:
  application:
    name: "twitt"
  cloud:
    function:
      definition: convertPostCdcToPostMessage;test;
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            processing:
              guarantee: exactly_once
      bindings:
        # Post Transformer
        convertPostCdcToPostMessage-in-0:
          destination: post-created
        convertPostCdcToPostMessage-out-0:
          destination: post-transformed
          producer:
            partition-count: 1
        test-in-0:
          destination: post-transformed

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG